/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegopantallas.frames;

import javax.swing.JOptionPane;
import juego.usuario;

/**
 *
 * @author Soulshiryu
 */
public class FrameConfJugador extends javax.swing.JFrame {
 
    FrameLobby frame3= new FrameLobby();
   
    /**
     * Creates new form Configuracion_Partida
     */
    public FrameConfJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Continuar_a_configurancionJuego = new javax.swing.JButton();
        cb_establecerColor = new javax.swing.JComboBox();
        txtnomjugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_Continuar_a_configurancionJuego.setText("Continuar");
        btn_Continuar_a_configurancionJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Continuar_a_configurancionJuegoActionPerformed(evt);
            }
        });

        cb_establecerColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "azul", "amarillo", "rojo", "verde" }));

        txtnomjugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomjugadorKeyTyped(evt);
            }
        });

        jLabel1.setText("Color de ficha:");

        jLabel2.setText("Nombre de jugador:");

        jLabel3.setText("Configuracion De Jugador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnomjugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_establecerColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Continuar_a_configurancionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_establecerColor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btn_Continuar_a_configurancionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Continuar_a_configurancionJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Continuar_a_configurancionJuegoActionPerformed
             if(validarCampos()==false){
                 
                 frame3.setVisible(true);
                 usuario u = new usuario();
                 u.setNombre(txtnomjugador.getText());
                 String color = (String) cb_establecerColor.getSelectedItem();
                 u.setColor(color);
                 
                    if (validarUsuarios(u)==false) {
                 /*
                     Codigo para asignar numeracion de jugadores temportal
                     */    
                     if ( FrameLobby.JLjugador1.getText().equals("espacio disponible")) {
                         FrameLobby.JLjugador1.setText(u.getNombre());
                         FrameLobby.txt_color1.setText(u.getColor());
                
                     }else if(FrameLobby.JLjugador2.getText().equalsIgnoreCase("espacio disponible")){
                         FrameLobby.JLjugador2.setText(u.getNombre());
                         FrameLobby.txt_color2.setText(u.getColor());
                 
                     }else if(FrameLobby.JLjugador3.getText().equalsIgnoreCase("espacio disponible")){
                         FrameLobby.JLjugador3.setText(u.getNombre());
                         FrameLobby.txt_color3.setText(u.getColor());
                         
                     }else if(FrameLobby.JLjugador4.getText().equalsIgnoreCase("espacio disponible")){
                         FrameLobby.JLjugador4.setText(u.getNombre());
                         FrameLobby.txt_color4.setText(u.getColor());
                     }
                 /*
                     Codigo para asignar numeracion de jugadores temportal
                     */    
                 }
                    
                   /*
                    temporal mente desactive el dispose, para que se puedan ir agregando diferentes jugadores, lo que pasa es que en la linea 16 se crea un frame configuracion_juego diferente
                    por lo tando mientras no tengamos los metodos de conexion se mantrenda el dispose como comentado.
                    */
//                 dispose();
             }
             
             
      
    }//GEN-LAST:event_btn_Continuar_a_configurancionJuegoActionPerformed

    private void txtnomjugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomjugadorKeyTyped
        // TODO add your handling code here:
        validarcaracteres(evt);
      
    }//GEN-LAST:event_txtnomjugadorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConfJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConfJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConfJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConfJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConfJugador().setVisible(true);
            }
        });
        
    }
        public boolean validarCampos() {
        if (txtnomjugador.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Establece color y nombre de jugador para empezar");
        return true;
        }
        return false;
    }
        
        public boolean validarUsuarios(usuario u) {
        if (u.getNombre().equals(FrameLobby.JLjugador1.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FrameLobby.JLjugador2.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FrameLobby.JLjugador3.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FrameLobby.JLjugador4.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        
        if (u.getColor().equals(FrameLobby.txt_color1.getText()) ) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FrameLobby.txt_color2.getText()) ) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FrameLobby.txt_color3.getText()) ) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FrameLobby.txt_color4.getText()) ) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        
        return false;
    }
        public void validarcaracteres(java.awt.event.KeyEvent evento){
         if (evento.getKeyChar ( ) >=33 && evento.getKeyChar()<= 47
        || evento.getKeyChar() >= 91 && evento.getKeyChar ( ) <= 96
        || evento.getKeyChar() >= 123 && evento.getKeyChar ( ) <= 208
        || evento.getKeyChar() >= 210 && evento.getKeyChar ( ) <= 240
        || evento.getKeyChar() >= 242 && evento.getKeyChar ( ) <=255 ) {
    evento.consume();
    JOptionPane.showMessageDialog ( this," No se permiten caracteres especiales" );
 }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Continuar_a_configurancionJuego;
    private javax.swing.JComboBox cb_establecerColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtnomjugador;
    // End of variables declaration//GEN-END:variables
}
